### ISSUE TITLE
[BUG] Unable to upload a resume using JSON

### ISSUE THREAD

**Issue by jcowley** [affinda/affinda-typescript#11]
**Describe the bug**
We're unable to upload a resume as JSON using the `ResumeUpload` object structure. When we attempt this, we're getting the error:

`TypeError: source.on is not a function`

**To Reproduce**
```
const credential = new AffindaCredential('token-goes-here');
const client = new AffindaAPI(credential);
const data = {
  name: {
    first: 'Joe',
    last: 'Smith',
  },
  workExperience: [{
    jobTitle: 'Bartender',
    organization: 'The Drink Tank'
  }]
};
const json = await client.createResume({ data: JSON.stringify(data) });
```

**Expected behavior**
A new resume is created in Affinda and the parsed resume response is returned from the client.

**Stacktrace / Screenshts**
```
TypeError: source.on is not a function
    at Function.DelayedStream.create (/server/node_modules/@azure/core-rest-pipeline/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/server/node_modules/@azure/core-rest-pipeline/node_modules/combined-stream/lib/combined_stream.js:45:37)
    at FormData.append (/server/node_modules/@azure/core-rest-pipeline/node_modules/form-data/lib/form_data.js:75:3)
    at prepareFormData (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:990:25)
    at Object.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:959:27)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at Object.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:619:20)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at Object.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:1198:20)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at Object.sendRequest (/server/node_modules/@azure/core-client/dist/index.js:1458:20)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at HttpPipeline.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:98:16)
    at AffindaAPI.sendRequest (/server/node_modules/@azure/core-client/dist/index.js:1886:30)
    at AffindaAPI.sendOperationRequest (/server/node_modules/@azure/core-client/dist/index.js:1948:44)
    at AffindaAPI.createResume (/server/node_modules/@affinda/affinda/dist/index.js:9417:21)
```
**Environment**
 - Client version: 5.3.1
 - NodeJS version v14.20.1

**Additional context**
Also tried passing the resume data as an object without stringifying it (`client.createResume({ data })`). It seems that this might be the correct way to do it, because it (correctly) caught and threw a validation error. But when I corrected the problem in the object structure, I get the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:1157:5)
    at FormData._getContentDisposition (/server/node_modules/@azure/core-rest-pipeline/node_modules/form-data/lib/form_data.js:231:21)
    at FormData._multiPartHeader (/server/node_modules/@azure/core-rest-pipeline/node_modules/form-data/lib/form_data.js:178:33)
    at FormData.append (/server/node_modules/@azure/core-rest-pipeline/node_modules/form-data/lib/form_data.js:71:21)
    at prepareFormData (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:990:25)
    at Object.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:959:27)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at Object.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:619:20)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at Object.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:1198:20)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at Object.sendRequest (/server/node_modules/@azure/core-client/dist/index.js:1458:20)
    at /server/node_modules/@azure/core-rest-pipeline/dist/index.js:95:31
    at HttpPipeline.sendRequest (/server/node_modules/@azure/core-rest-pipeline/dist/index.js:98:16)
    at AffindaAPI.sendRequest (/server/node_modules/@azure/core-client/dist/index.js:1886:30)
    at AffindaAPI.sendOperationRequest (/server/node_modules/@azure/core-client/dist/index.js:1948:44)
    at AffindaAPI.createResume (/server/node_modules/@affinda/affinda/dist/index.js:9417:21)
```

**Comment by jcowley** [comment]
Thought it might be the outdated version of node I was using. Updated to node v20.7.0, but I'm getting the same result.
