### ISSUE TITLE
[BUG] createJobDescription throws error

### ISSUE THREAD

**Issue by seatedro** [affinda/affinda-typescript#7]
## **Describe the bug**
Using the Node.js module to `createJobDescription` throws an error both when reading from a file and from a URL.

## **To Reproduce**
1. Run the sample `createJobDescription` template

## **Expected behavior**
The job description gets uploaded and parsed. An identifier is returned.

## **Stacktrace / Screenshots**
```
azure:core-client:warning The baseUri option for SDK Clients has been deprecated, please use endpoint instead.
azure:core-rest-pipeline retryPolicy:info Retry 0: Attempting to send request 0860de3c-2472-44eb-8779-b555158c210c
azure:core-rest-pipeline:info Request: {
  "url": "https://api.affinda.com/v2/job_descriptions",
  "headers": {
    "content-type": "multipart/form-data; boundary=--------------------------732956753034998471030541",
    "accept": "application/json",
    "accept-encoding": "gzip,deflate",
    "user-agent": "azsdk-js-affinda/2.5.0 core-rest-pipeline/1.10.0 Node/v16.13.1 OS/(x64-Windows_NT-10.0.22621)",
    "x-ms-client-request-id": "0860de3c-2472-44eb-8779-b555158c210c",
    "authorization": "REDACTED"
  },
  "method": "POST",
  "timeout": 0,
  "disableKeepAlive": false,
  "streamResponseStatusCodes": {},
  "withCredentials": false,
  "requestId": "0860de3c-2472-44eb-8779-b555158c210c",
  "allowInsecureConnection": false,
  "enableBrowserStreams": false
}
azure:core-rest-pipeline:info No cached TLS Agent exist, creating a new Agent
node:_http_outgoing:742
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (false)
    at new NodeError (node:internal/errors:371:5)
    at write_ (node:_http_outgoing:742:11)
    at ClientRequest.write (node:_http_outgoing:707:15)
    at FormData.ondata (node:internal/streams/legacy:20:31)
    at FormData.emit (node:events:390:28)
    at FormData.CombinedStream.write (E:\Work\affinda-test\node_modules\combined-stream\lib\combined_stream.js:138:8)
    at FormData.CombinedStream._pipeNext (E:\Work\affinda-test\node_modules\combined-stream\lib\combined_stream.js:126:8)
    at FormData.CombinedStream._realGetNext (E:\Work\affinda-test\node_modules\combined-stream\lib\combined_stream.js:99:10)
    at FormData.CombinedStream._getNext (E:\Work\affinda-test\node_modules\combined-stream\lib\combined_stream.js:82:12)
    at DelayedStream.emit (node:events:402:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Additionally 
```
https://api.affinda.com/static/sample_job_descriptions/example.pdf
```
This URL mentioned in the docs doesn't exist. The website throws a 404 not found. 
## **Environment**
 - Client version: [2.5.0]
 - NodeJS version [Tested on 16.15.1 and 16.13.1]
 - OS (Tested on both Windows and UNIX)

**Comment by seatedro** [comment]
This is working with version `2.5.1` now. Thanks for the quick fix 👍

**Comment by ghost** [comment]
Thanks for reporting the issue!
